### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/eurovision_contest_rank_analysis#31]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work! 

Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). -1 writing
**Comment:** As specified in your readme the project cannot be run from the root directory since the specific files required are present within the src folder and your command line instructions only specify the script name and not ```src/script_name```. So either add that to the individual commands or run the analysis from the src directory. 
- [ ] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added -1 quality
**Comment:** Missing author name and date in eurovision_preprocessing.py
- [ ] The proposal.md file has been created and moved to the doc directory -2 mechanics
**Comment:** Proposal.md is missing. 
- [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. -1 mechanics
- [ ] Challenging question- Tests arent present for any of the scripts. -7
